### ISSUE TITLE
Edisyn .Jar File for Linux

### ISSUE THREAD

**Issue by alasta4204** [eclab/edisyn#21]
Good Morning

I have downloaded the Zip file for ubuntu linux and I cannot find a .Jar file can anyone help please ? 

Many Thanks

Alastair

**Comment by eclab** [comment]
There is no zip file for "ubuntu linux".  What did you download?

The link to the jar file is located right at the Linux installation instructions on the front page for edisyn.  See https://github.com/eclab/edisyn

**Comment by alasta4204** [comment]
Thanks for getting back to me so quickly ! This is download link I am
clicking on "
Installation and Running on Linux
I get the option of saving it which uncompresses a load of files

or opening it which gives an error about it being executable


[image: image.jpeg]

I am using :

Distributor ID: Ubuntu
Description: Ubuntu 18.04.4 LTS
Release: 18.04
Codename: bionic

**Comment by alasta4204** [comment]
Okay I have made progress  , needed to do chmod +x edisyn.jar . Couldnt
make it executable in the  GUI

Thanks again

**Comment by eclab** [comment]
jar files are archives, like tar and zip.  But you don't want to unarchive it -- it sounds like your linux distro has decided to stupidly give you the option of unarchiving jar files.  

So anyway, now you have a jar file.  Since you're in ubuntu, you don't want to make it executable -- it's not an executable!  Rather, you want to set it up so when you double-click on it, the jar file is launched by your Java VM.  There are instructions to do that in Ubuntu right at the installation instructions where you found the jar file link.  It's step number 2.

**Comment by triclops200** [comment]
Or you can just make it an executable like you did. Executable means that the system is allowed to look up a program to run that with if you try to run it. 
On linux systems, at least, the system uses the first few bytes of the file to figure out how to run it. For jars, the first two bytes are the ascii PK.  When it sees the executable flag set (chmod +x) and those first two bytes, it'll call java to run the jar. You can avoid this process by following the instructions stated above, but it can cause a security risk in rare circumstances.

**Comment by alasta4204** [comment]
Thank you again running fine now , looks really good.  Ubuntu was unpacking
the.  Jar  file , and being ubuntu studio the file manager ( Thunar ) has
no option to make it executable , needs to be done in a terminal.

Many thanks for your help

Alastair
