### ISSUE TITLE
Multi-mode for TX802

### ISSUE THREAD

**Issue by elektronen** [eclab/edisyn#29]
I have been using Edisyn for several months with Roland D-110, Yamaha FB-01, and Yamaha TX7. Recently I decided to upgrade from the TX7 to a TX802, and was disappointed to find the much nicer TX802 is not as well supported as the FB-01 or other 4-op synths, with the seeming expectation that the DX7 editor would be good enough. I'm afraid that's not the case, as the TX802 is like a DX7II with a layer of the FB-01's multi-timbrality added on top.

Is there any way the multi mode of the TX802 could get some support in Edisyn? I would very much like be be able to assign voices and polyphony, as well as control effects, using Edisyn.

**Comment by eclab** [comment]
It's not easy for me to build editors for synthesizers I don't own or have on ultra-long-term loan, since I have to maintain and debug them over time.  So if you gifted me a TX802...

That being said, I am considering adding some support for the (non-multitimbral aspects of) the DX7II/FD, which would also help out for the TX802, with the help of one or two DX7II owners.  But it will be tricky as I won't have one to debug at all.

Effects are out I'm afraid: effects are unbelievably hard to write editors for, and there's no way I could do that without owning a unit.  :-(  Multitimbral support is also unlikely for the same reason.

Sean
