### ISSUE TITLE
Select directory problem on macos

### ISSUE THREAD

**Issue by samstaton** [eclab/edisyn#41]
In Batch Download, "select directory" is causing a null pointer exception on macos 10.14.6. So batch download doesn't work. Fix seems to be:

```
Synth.java
6960c6960
<                 return new File(fd.getFile());
---
>                 return new File(fd.getDirectory());
```

**Comment by SeanLuke** [comment]
Unfortunately this doesn't work.  getDirectory() choose the *parent* of the chosen directory.  Since getFile() is returning null, this is very bad news -- we'll have to go back to JFileChooser for making new directories.  :-(

**Comment by samstaton** [comment]
Ah, it is working for me, but it may be specific to different macos versions. 

My experiments suggested that the chooser picks a new _file_ (you seem to _have_ to give a file name when you use it, even though we are wanting to choose a directory, not a file, so I just leave the file name as "Untitled"). And getDirectory() is returning the directory where you chose to put the file, which is the directory that you want. Whereas getFile() is just returning the string of the short file name (e.g. Untitled), and so getParent of that string is null.

**Comment by eclab** [comment]
This is the case for me too.  But unfortunately that's not how the Mac interface is supposed to work; for example, let's say you clicked on a file in an ordinary save panel.  That file would then appear in the "Save as:" text box.  But here, if you click on a directory (notionally the target "file" of a FileChooser set up on the Mac to select directories) it doesn't appear in the text box -- it just works like how you normally click on directories.  :-(  

We can't use the "Load" file chooser because the button says "Open".  

The only alternatives would be (1) to use the horrific JFileChooser or (2) change the default filename in the Save box to something like "Choose a Directory".  I think it'd be very confusing though.  Do you have any suggestions for the text for #2?  It's gotta be [A] short [B] informs the user that he needs to pick a directory, then press "save" [3] make it clear that he can't type a directory name in the save text box.

**Comment by samstaton** [comment]
Ah, I tried the "Load" file chooser and I think it works much more intuitively. I see what you mean about "Open", but it is not too bad, since you are genuinely opening the _folder_ in which the patches should be saved. With the "Save" file chooser, I can't select the folder that I want, I have to go into its parent folder and then manually type its name, which is a bit weird, and then I get a warning that it already exists and will be overwritten, which is not really true -- I mean existing files in the folder aren't touched unless there is a name overlap. 

(For either of these options I think line 6960 should be `return new File(fd.getDirectory(), fd.getFile());`.)

**Comment by eclab** [comment]
> On Sep 8, 2021, at 12:22 PM, samstaton ***@***.***> wrote:
> 
> Ah, I tried the "Load" file chooser and I think it works much more intuitively. I see what you mean about "Open", but it is not too bad, since you are genuinely opening the folder in which the patches should be saved.
> 
Well the other problem is that you can't create a folder to "open" in the Load file chooser -- you have to select an existing folder.  :-(  Of course this is the same misfeature that JFileChooser has.
> .(For either of these options I think line 6960 should be return new File(fd.getDirectory(), fd.getFile());.)
> 
Are you sure?  Why not just getFile()?

**Comment by samstaton** [comment]
Oh, on my macos, I get a "new folder" button in the Load file chooser (bottom left), so it is all working nicely. 

For me, `fd.getFile()` just returns the file name without path, and so I'm getting a null pointer when you later take it's parent. But `new File(fd.getDirectory(), fd.getFile());` seems to work fine, no null pointers.

**Comment by SeanLuke** [comment]
Thanks for the excellent bug report.  I've committed code using just `FileDialog.LOAD` and `new File(fd.getDirectory(), fd.getFile());`  I'm closing this issue for now, but reopen it if I screwed something up.
