### ISSUE TITLE
Hill-Climb Locks up

### ISSUE THREAD

**Issue by Disgraceland** [eclab/edisyn#5]
Wavestation SR Performance Mode
Mac - Latest OS

1. Not all selections play (autoplay is running)
2. Application locks after a short while
3. Seemed to perform a reset on the SR

Possibly going from selection to selection too quickly?

**Comment by eclab** [comment]
Could you provide some more information, specifically:

> Wavestation SR Performance Mode

Do these issues happen when hill-climbing Patches, or just Performances?

> Mac - Latest OS

- What version of OS X are you running exactly?  
- What version of Java?

- What version of the SR Firmware are you running?  This could have a big impact.  To find out, press BANK + EDIT + YES, and while pressing them, hit CURSOR DOWN.  Edisyn was written to target version 1.15.

> 	• Application locks after a short while

- Which application?  Edisyn is freezing?  Or did you mean something on the SR?

> 	• Not all selections play (autoplay is running)
> 	• Seemed to perform a reset on the SR
> Possibly going from selection to selection too quickly?

Sounds like the buffer is getting overrun on the SR.  That's fixable, I'll have to slow things down even more.  :-(  It would be unusual to be hanging Edisyn.

Sean

**Comment by eclab** [comment]
I've made some fixes.  There were two bugs I identified.  (1) The SR is weird in that it needs extra time after accepting a sysex dump due to its interface animation, even though it can immediately start playing that dump.  So I've added a 1.1 second pause in the hill-climber which is sufficient to not overload the sysex buffer.  And (2) a dumb bug in the hill-climber caused Edisyn to produce null models, thus creating the "hanging" you saw.  Both should be working now.  I have tested on Patch and Performance and they work well: Wave Sequence hasn't been tested.

**Comment by Disgraceland** [comment]
Hi Sean

OS 10.12.6
Java - Don't know. How can I tell?
Only tested performances. Can't comment on patches. Will test later.
SR version 1.15
Application lock - Edisyn

Cheers,
John

**Comment by Disgraceland** [comment]
Edisyn locks up - Fixed
SR SYSex load issues - still there. Best that I have had is playing every other one.
 Could you add a control to allow me to define the wait between each patch load?
Cheers
John
P.S my java version was Java 8 Update 10.1. I'm upgrading it now

**Comment by eclab** [comment]
Java version 8 should be just fine.

I have uploaded a special version of Edisyn (for testing) to http://cs.gmu.edu/~sean/temp/EdisynHillClimb.app.zip

It has a Delay knob in Performance, next to the patch name, which defines values in milliseconds.  The value that Edisyn normally is using for Performance patches is 1100 ms.  Find the smallest value which seems to be working consistently and let me know what it is: you should be able to tell because the "Receiving Sysex" animation will just barely drop back to the patch display on the SR screen before Edisyn sends the next sysex (bringing up the "Receiving Sysex" animation again).  I had found that 1100ms is the right amount.

BTW, "Not all selections play" may not be a bug at all -- there are a number of parameters with certain values which will prevent any sound from playing, and so a patch which has set them randomly to those values will not make any sound.  It's often the case that certain patch dumps from the hill-climber will seemingly not play.

**Comment by Disgraceland** [comment]
Just downloading this now.

**Comment by eclab** [comment]
Any results?

**Comment by eclab** [comment]
Assuming that no news is good news, I'm closing this issue for the time being.
